<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * custom_completion.php
 *
 * @package   mod_flexbook
 * @copyright 2026 Eduardo Kraus {@link https://eduardokraus.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace mod_flexbook\completion;

use core_completion\activity_custom_completion;
use mod_flexbook\progress\progress_manager;
use Override;

/**
 * Evaluates the custom FlexBook activity completion rules.
 */
class custom_completion extends activity_custom_completion {
    /**
     * Gets the current state of a custom completion rule.
     *
     * @param string $rule Completion rule name.
     * @return int
     */
    #[Override]
    public function get_state(string $rule): int {
        $this->validate_rule($rule);

        $manager = new progress_manager();
        return $manager->completion_requirements_met($this->cm->instance, $this->userid)
            ? COMPLETION_COMPLETE
            : COMPLETION_INCOMPLETE;
    }

    /**
     * Gets the custom completion rules supported by FlexBook.
     *
     * completionpercentage is kept as a legacy alias so cached course-module data
     * generated by FlexBook 1.1.6 and earlier does not break activity rendering.
     *
     * @return array
     */
    #[Override]
    public static function get_defined_custom_rules(): array {
        return ["completionmode", "completionpercentage"];
    }

    /**
     * Gets descriptions for the configured custom completion rules.
     *
     * @return array
     */
    #[Override]
    public function get_custom_rule_descriptions(): array {
        $customdata = (array) $this->cm->customdata;
        $percentage = $customdata["completionpercentage"]
            ?? $customdata["customcompletionrules"]["completionpercentage"]
            ?? 80;
        $description = get_string("completiondescription", "mod_flexbook", $percentage);

        return [
            "completionmode" => $description,
            "completionpercentage" => $description,
        ];
    }

    /**
     * Gets all completion rules in their display order.
     *
     * @return array
     */
    #[Override]
    public function get_sort_order(): array {
        return [
            "completionview",
            "completionmode",
            "completionpercentage",
            "completionusegrade",
            "completionpassgrade",
        ];
    }
}
